"""empty message

Revision ID: d98c1e128665
Revises: 9c301e005c4a
Create Date: 2026-07-30 11:40:52.931275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98c1e128665'
down_revision = '9c301e005c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))
        batch_op.drop_column('imge_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imge_path', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
